import Header from '@/components/Header/Header';
import Main from '@/components/Main/Main';
import StoreProvider from '@/components/StoreProvider/StoreProvider';
import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<StoreProvider>
			<Main>
				<html lang="ru">
					<body>
						<Header />
						<main>{children}</main>
					</body>
				</html>
			</Main>
		</StoreProvider>
	);
}
